CREATE TABLE IF NOT EXISTS metars (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  station_id TEXT NOT NULL,
  observation_time TIMESTAMP NOT NULL,
  raw_text TEXT NOT NULL,
  data JSONB NOT NULL
);