version: '3'

services:
  db:
    image: postgres:latest
    container_name: aviation_weather_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgress}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-aviation_weather}
    volumes:
     - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped