x-env_file: &env
  - path: .env
    required: true
  - path: .env.local
    required: false

name: aviation
services:
  db:
    image: postgis/postgis:latest
    container_name: aviation-db
    env_file: *env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
     - db:/var/lib/postgresql/data
     - db_logs:/var/log
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - backend
    profiles:
      - backend
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: aviation-redis
    volumes:
      - redis:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - backend
    profiles:
      - backend
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: aviation-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_PORT_INTERNAL:-9001}:9001
    networks:
      - backend
    profiles:
      - backend
    command: server --console-address ":9001" /data
    restart: unless-stopped

  api:
    container_name: aviation-api
    env_file: *env
    ports:
      - "${SERVICE_PORT:-5000}:5000"
    build:
      context: service
    depends_on:
      - db
      - redis
      - minio
    networks:
      - frontend
      - backend
    profiles:
      - api
    restart: unless-stopped

  ui:
    container_name: aviation-ui
    env_file: *env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - ${UI_PORT:-3000}:3000
    build:
      context: ./ui/
      target: dev
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/styles:/app/styles
    networks:
      - frontend
    profiles:
      - frontend
    command: ["npm", "run", "dev"]
    restart: unless-stopped

volumes:
  db:
  db_logs:
  redis:
  minio:

networks:
  frontend:
  backend:
