version: '3'

services:
  db:
    image: postgres:latest
    container_name: aviation-weather_db
    environment:
      POSTGRES_USER: ${POSTRGRES_USER}
      POSTGRESS_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      -'5432:5432'
    restart: unless-stopped