version: '3'

services:
  weather-db:
    image: postgis/postgis:latest
    container_name: weather.db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
     - db:/var/lib/postgresql/data
     - db_logs:/var/log
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped

volumes:
  db:
  db_logs: