version: '3'

services:
  db:
    image: postgres:latest
    container_name: weather.db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
     - db_weather:/var/lib/postgresql/data
     - db_logs_weather:/var/log
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  db_weather:
  db_logs_weather: