CREATE TABLE "metars" (
    id SERIAL PRIMARY KEY,
    icao TEXT NOT NULL,
    raw_text TEXT NOT NULL,
    station_id TEXT NOT NULL,
    observation_time TEXT NOT NULL,
    latitude INTEGER NOT NULL,
    longitude INTEGER NOT NULL,
    temp_c DOUBLE PRECISION NOT NULL,
    dewpoint_c DOUBLE PRECISION NOT NULL,
    wind_dir_degrees INTEGER NOT NULL,
    wind_speed_kt INTEGER NOT NULL,
    visibility_statute_mi TEXT NOT NULL,
    altim_in_hg DOUBLE PRECISION NOT NULL,
    sea_level_pressure_mb DOUBLE PRECISION,
    wx_string TEXT,
    flight_category TEXT,
    three_hr_pressure_tendency_mb DOUBLE PRECISION,
    metar_type TEXT,
    max_t_c DOUBLE PRECISION,
    min_t_c DOUBLE PRECISION,
    precip_in DOUBLE PRECISION,
    elevation_m INTEGER
)