import React from 'react';
import RecoilRootWrapper from '@app/recoil-root-wrapper';
import Sidebar from '@/components/Sidebar';
import Topbar from '@/components/Topbar';
import 'styles/globals.css';
import 'styles/leaflet.css';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='h-full bg-white'>
      <head>
        <title>Aviation Weather</title>
      </head>
      <body className={`${inter.className} wrapper h-full`}>
        <RecoilRootWrapper>
          <StyledComponentsRegistry>
            <Topbar />
            <Sidebar />
            {children}
          </StyledComponentsRegistry>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
