version: '3'

name: aviation
services:
  ui:
    container_name: aviation-ui
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - ${UI_PORT:-3000}:3000
    build:
      context: ./
      target: dev
      tags:
        - aviation-ui:${TAG:-latest}
    command: "npm run dev"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
